---
title: "Annual Meetings"
output:
  html_document:
    #code_folding: hide
    toc: false
    toc_float: true
    collapsed: true
    number_sections: false
    toc_depth: 3
---

```{=html}
<style>
  .nav-pills>li>a:hover, .nav-pills>li>a:focus, .nav-pills>li.active>a,     .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus{
     background-color: CadetBlue; 
     }
</style>
```
<!-- https://www.angularfix.com/2021/10/how-to-change-tabset-colors-without.html -->

```{r setup, include=FALSE}
    knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

#  {.tabset .tabset-fade .tabset-pills}

The 6th SCSC workshop is provisionally scheduled to be held in Rio de Janeiro (Brazil) in September 2023, organised by Marcus Maia and Bruna Franchetto.

## Madrid (2022)

The 5th SCSC workshop was held at the beautiful [Princesa campus](https://www.nebrija.com/la_universidad/visita-virtual/como-llegar-nebrija.php) in the heart of Madrid on 2 and 3 May 2022, organized by Jon Duñabeitia.

The event will be hosted in connection with the [ACELERA](https://www.nebrija.com/investigacion-universidad/red-acelera/) Network and as a satellite event to the International [APPE-SEPEX](https://appesepexmeeting.appe.pt/) Meeting that will be held in Faro (Portugal) between 5-7 May 2022.

## Kaiserslauten (2021)


The 4th SCSC workshop was held in Frankenstein/Kaiserslautern, Germany, from 1 to 3 October 2021, organized by Thomas Lachmann, Réka Vágvölgyi, Aleksandar Bulajić, and Kirstin Bergstroem.

[Kaiserslautern meeting program](https://culturalbrain.org/wp-content/uploads/2021/11/Kaiserslautern-meeting-program.pdf)

## Goa (2020)

The 3rd SCSC workshop was held at BITS Pilani University in Goa (India) from 3 to 7 February 2020 and hosted by Veeky Baths (BITS Pilani University Goa), Ramesh Mishra (University of Hyderabad), and Falk Huettig (Max Planck & Radboud University Nijmegen).

[Goa meeting program](https://culturalbrain.org/wp-content/uploads/2021/11/Goa-meeting-program.pdf)

## Haifa (2019)

The 2nd SCSC workshop was held on Mount Carmel at the University of Haifa, Israel, from 18 to 20 February 2019, organized by Zohar Eviatar and Tali Bitan.

[Haifa meeting program](https://culturalbrain.org/wp-content/uploads/2019/04/Program_Haifa2019_ws_SCSC.pdf)


## Founding Meeting - Lisbon (2018)

The Founding Meeting was held on 21 and 22 June 2018 in Lisbon, Portugal and was organised by Tânia Fernandes and Susana Araujo (University of Lisbon).

[Lisbon meeting program](https://culturalbrain.org/wp-content/uploads/2019/04/Program_IWCSC_June_2018.pdf)

[Speaker Biographies](https://culturalbrain.org/wp-content/uploads/2019/04/NotasBiogr%C3%A1ficas.pdf)

